name: test
on:
  pull_request:
    branches: ["main"]

jobs:
  testing:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: node_modules cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('yarn.lock') }}
          restore_keys: node_modules-

      - name: Yarn install
        run: yarn

      - name: Tests
        run: yarn test
